#!/bin/sh
if [ "$#" -ne 1 ]
then
	echo "Usage: $0 application" 1>&2
	exit 1
fi
application=$1

if [ "$application" = ignored ]
then
	exit 0
fi

folder=`get_table_name $application folder`
relation=`get_table_name $application relation`
attribute=`get_table_name $application attribute`
folder_attribute=`get_table_name $application folder_attribute`
role_folder=`get_table_name $application role_folder`
row_security_role_update=`get_table_name $application row_security_role_update`
subschemas=`get_table_name $application subschemas`
role_operation=`get_table_name $application role_operation`

(
cat << all_done
delete from $folder where folder = 'account';
delete from $relation where folder = 'account';
delete from $attribute where attribute = 'account';
delete from $attribute where attribute = 'subclassification';
delete from $attribute where attribute = 'hard_coded_account_key';
delete from $folder_attribute where folder = 'account';
delete from $folder where folder = 'bank_upload';
delete from $relation where folder = 'bank_upload';
delete from $attribute where attribute = 'bank_date';
delete from $attribute where attribute = 'bank_description';
delete from $attribute where attribute = 'sequence_number';
delete from $attribute where attribute = 'bank_amount';
delete from $attribute where attribute = 'bank_running_balance';
delete from $attribute where attribute = 'posted_yn';
delete from $folder_attribute where folder = 'bank_upload';
delete from $folder where folder = 'day';
delete from $relation where folder = 'day';
delete from $attribute where attribute = 'day';
delete from $folder_attribute where folder = 'day';
delete from $folder where folder = 'depreciation';
delete from $relation where folder = 'depreciation';
delete from $attribute where attribute = 'full_name';
delete from $attribute where attribute = 'street_address';
delete from $attribute where attribute = 'depreciation_date';
delete from $attribute where attribute = 'purchase_date_time';
delete from $attribute where attribute = 'asset_name';
delete from $attribute where attribute = 'transaction_date_time';
delete from $attribute where attribute = 'serial_number';
delete from $attribute where attribute = 'units_produced';
delete from $attribute where attribute = 'depreciation_amount';
delete from $folder_attribute where folder = 'depreciation';
delete from $folder where folder = 'depreciation_method';
delete from $relation where folder = 'depreciation_method';
delete from $attribute where attribute = 'depreciation_method';
delete from $folder_attribute where folder = 'depreciation_method';
delete from $folder where folder = 'element';
delete from $relation where folder = 'element';
delete from $attribute where attribute = 'element';
delete from $attribute where attribute = 'accumulate_debit_yn';
delete from $folder_attribute where folder = 'element';
delete from $folder where folder = 'entity';
delete from $relation where folder = 'entity';
delete from $attribute where attribute = 'full_name';
delete from $attribute where attribute = 'street_address';
delete from $attribute where attribute = 'login_name';
delete from $attribute where attribute = 'city';
delete from $attribute where attribute = 'state_code';
delete from $attribute where attribute = 'zip_code';
delete from $attribute where attribute = 'phone_number';
delete from $attribute where attribute = 'cell_number';
delete from $attribute where attribute = 'email_address';
delete from $folder_attribute where folder = 'entity';
delete from $folder where folder = 'equity_account_balance';
delete from $relation where folder = 'equity_account_balance';
delete from $attribute where attribute = 'full_name';
delete from $attribute where attribute = 'street_address';
delete from $attribute where attribute = 'account_number';
delete from $attribute where attribute = 'date_time';
delete from $attribute where attribute = 'investment_operation';
delete from $attribute where attribute = 'transaction_date_time';
delete from $attribute where attribute = 'share_price';
delete from $attribute where attribute = 'share_quantity_change';
delete from $attribute where attribute = 'share_quantity_balance';
delete from $attribute where attribute = 'moving_share_price';
delete from $attribute where attribute = 'unrealized_gain_balance';
delete from $attribute where attribute = 'unrealized_gain_change';
delete from $attribute where attribute = 'realized_gain';
delete from $folder_attribute where folder = 'equity_account_balance';
delete from $folder where folder = 'financial_institution';
delete from $relation where folder = 'financial_institution';
delete from $attribute where attribute = 'full_name';
delete from $attribute where attribute = 'street_address';
delete from $folder_attribute where folder = 'financial_institution';
delete from $folder where folder = 'fixed_asset';
delete from $relation where folder = 'fixed_asset';
delete from $attribute where attribute = 'asset_name';
delete from $attribute where attribute = 'account';
delete from $folder_attribute where folder = 'fixed_asset';
delete from $folder where folder = 'fixed_asset_purchase';
delete from $relation where folder = 'fixed_asset_purchase';
delete from $attribute where attribute = 'full_name';
delete from $attribute where attribute = 'street_address';
delete from $attribute where attribute = 'purchase_date_time';
delete from $attribute where attribute = 'asset_name';
delete from $attribute where attribute = 'serial_number';
delete from $attribute where attribute = 'extension';
delete from $attribute where attribute = 'estimated_useful_life_years';
delete from $attribute where attribute = 'estimated_useful_life_units';
delete from $attribute where attribute = 'declining_balance_n';
delete from $attribute where attribute = 'depreciation_method';
delete from $attribute where attribute = 'accumulated_depreciation';
delete from $attribute where attribute = 'disposal_date';
delete from $folder_attribute where folder = 'fixed_asset_purchase';
delete from $folder where folder = 'investment_account';
delete from $relation where folder = 'investment_account';
delete from $attribute where attribute = 'full_name';
delete from $attribute where attribute = 'street_address';
delete from $attribute where attribute = 'account_number';
delete from $attribute where attribute = 'classification';
delete from $attribute where attribute = 'investment_account';
delete from $attribute where attribute = 'certificate_maturity_months';
delete from $attribute where attribute = 'certificate_maturity_date';
delete from $attribute where attribute = 'interest_rate';
delete from $folder_attribute where folder = 'investment_account';
delete from $folder where folder = 'investment_classification';
delete from $relation where folder = 'investment_classification';
delete from $attribute where attribute = 'classification';
delete from $folder_attribute where folder = 'investment_classification';
delete from $folder where folder = 'investment_operation';
delete from $relation where folder = 'investment_operation';
delete from $attribute where attribute = 'investment_operation';
delete from $folder_attribute where folder = 'investment_operation';
delete from $folder where folder = 'journal_ledger';
delete from $relation where folder = 'journal_ledger';
delete from $attribute where attribute = 'full_name';
delete from $attribute where attribute = 'street_address';
delete from $attribute where attribute = 'transaction_date_time';
delete from $attribute where attribute = 'account';
delete from $attribute where attribute = 'transaction_count';
delete from $attribute where attribute = 'previous_balance';
delete from $attribute where attribute = 'debit_amount';
delete from $attribute where attribute = 'credit_amount';
delete from $attribute where attribute = 'balance';
delete from $folder_attribute where folder = 'journal_ledger';
delete from $folder where folder = 'prior_fixed_asset';
delete from $relation where folder = 'prior_fixed_asset';
delete from $attribute where attribute = 'asset_name';
delete from $attribute where attribute = 'serial_number';
delete from $attribute where attribute = 'extension';
delete from $attribute where attribute = 'recorded_date';
delete from $attribute where attribute = 'estimated_useful_life_years';
delete from $attribute where attribute = 'estimated_useful_life_units';
delete from $attribute where attribute = 'declining_balance_n';
delete from $attribute where attribute = 'depreciation_method';
delete from $attribute where attribute = 'disposal_date';
delete from $attribute where attribute = 'full_name';
delete from $attribute where attribute = 'street_address';
delete from $attribute where attribute = 'transaction_date_time';
delete from $attribute where attribute = 'accumulated_depreciation';
delete from $folder_attribute where folder = 'prior_fixed_asset';
delete from $folder where folder = 'prior_fixed_asset_depreciation';
delete from $relation where folder = 'prior_fixed_asset_depreciation';
delete from $attribute where attribute = 'full_name';
delete from $attribute where attribute = 'street_address';
delete from $attribute where attribute = 'asset_name';
delete from $attribute where attribute = 'serial_number';
delete from $attribute where attribute = 'depreciation_date';
delete from $attribute where attribute = 'depreciation_amount';
delete from $attribute where attribute = 'transaction_date_time';
delete from $folder_attribute where folder = 'prior_fixed_asset_depreciation';
delete from $folder where folder = 'purchase_order';
delete from $relation where folder = 'purchase_order';
delete from $attribute where attribute = 'full_name';
delete from $attribute where attribute = 'street_address';
delete from $attribute where attribute = 'purchase_date_time';
delete from $attribute where attribute = 'amount_due';
delete from $attribute where attribute = 'sum_extension';
delete from $attribute where attribute = 'purchase_amount';
delete from $attribute where attribute = 'title_passage_rule';
delete from $attribute where attribute = 'shipped_date';
delete from $attribute where attribute = 'arrived_date_time';
delete from $attribute where attribute = 'transaction_date_time';
delete from $folder_attribute where folder = 'purchase_order';
delete from $folder where folder = 'receipt_upload';
delete from $relation where folder = 'receipt_upload';
delete from $attribute where attribute = 'receipt_upload_filename';
delete from $attribute where attribute = 'upload_date';
delete from $attribute where attribute = 'posted_yn';
delete from $folder_attribute where folder = 'receipt_upload';
delete from $folder where folder = 'reoccurring_transaction';
delete from $relation where folder = 'reoccurring_transaction';
delete from $attribute where attribute = 'full_name';
delete from $attribute where attribute = 'street_address';
delete from $attribute where attribute = 'debit_account';
delete from $attribute where attribute = 'credit_account';
delete from $attribute where attribute = 'transaction_amount';
delete from $folder_attribute where folder = 'reoccurring_transaction';
delete from $folder where folder = 'self';
delete from $relation where folder = 'self';
delete from $attribute where attribute = 'full_name';
delete from $attribute where attribute = 'street_address';
delete from $folder_attribute where folder = 'self';
delete from $folder where folder = 'service_purchase';
delete from $relation where folder = 'service_purchase';
delete from $attribute where attribute = 'full_name';
delete from $attribute where attribute = 'street_address';
delete from $attribute where attribute = 'purchase_date_time';
delete from $attribute where attribute = 'account';
delete from $attribute where attribute = 'service_description';
delete from $attribute where attribute = 'extension';
delete from $folder_attribute where folder = 'service_purchase';
delete from $folder where folder = 'subclassification';
delete from $relation where folder = 'subclassification';
delete from $attribute where attribute = 'subclassification';
delete from $attribute where attribute = 'element';
delete from $attribute where attribute = 'display_order';
delete from $folder_attribute where folder = 'subclassification';
delete from $folder where folder = 'supply';
delete from $relation where folder = 'supply';
delete from $attribute where attribute = 'supply_name';
delete from $attribute where attribute = 'account';
delete from $folder_attribute where folder = 'supply';
delete from $folder where folder = 'supply_purchase';
delete from $relation where folder = 'supply_purchase';
delete from $attribute where attribute = 'full_name';
delete from $attribute where attribute = 'street_address';
delete from $attribute where attribute = 'purchase_date_time';
delete from $attribute where attribute = 'supply_name';
delete from $attribute where attribute = 'quantity';
delete from $attribute where attribute = 'unit_cost';
delete from $attribute where attribute = 'extension';
delete from $folder_attribute where folder = 'supply_purchase';
delete from $folder where folder = 'tax_form';
delete from $relation where folder = 'tax_form';
delete from $attribute where attribute = 'tax_form';
delete from $folder_attribute where folder = 'tax_form';
delete from $folder where folder = 'tax_form_line';
delete from $relation where folder = 'tax_form_line';
delete from $attribute where attribute = 'tax_form';
delete from $attribute where attribute = 'tax_form_line';
delete from $attribute where attribute = 'tax_form_description';
delete from $attribute where attribute = 'itemize_accounts_yn';
delete from $folder_attribute where folder = 'tax_form_line';
delete from $folder where folder = 'tax_form_line_account';
delete from $relation where folder = 'tax_form_line_account';
delete from $attribute where attribute = 'tax_form';
delete from $attribute where attribute = 'tax_form_line';
delete from $attribute where attribute = 'account';
delete from $folder_attribute where folder = 'tax_form_line_account';
delete from $folder where folder = 'transaction';
delete from $relation where folder = 'transaction';
delete from $attribute where attribute = 'full_name';
delete from $attribute where attribute = 'street_address';
delete from $attribute where attribute = 'transaction_date_time';
delete from $attribute where attribute = 'memo';
delete from $attribute where attribute = 'transaction_amount';
delete from $attribute where attribute = 'check_number';
delete from $attribute where attribute = 'lock_transaction_yn';
delete from $folder_attribute where folder = 'transaction';
delete from $folder where folder = 'vendor';
delete from $relation where folder = 'vendor';
delete from $attribute where attribute = 'full_name';
delete from $attribute where attribute = 'street_address';
delete from $folder_attribute where folder = 'vendor';
delete from $folder where folder = 'vendor_payment';
delete from $relation where folder = 'vendor_payment';
delete from $attribute where attribute = 'full_name';
delete from $attribute where attribute = 'street_address';
delete from $attribute where attribute = 'purchase_date_time';
delete from $attribute where attribute = 'payment_date_time';
delete from $attribute where attribute = 'payment_amount';
delete from $attribute where attribute = 'check_number';
delete from $attribute where attribute = 'transaction_date_time';
delete from $folder_attribute where folder = 'vendor_payment';
all_done
) | sql.e 2>&1 | grep -iv duplicate

table_name=`get_table_name $application account`
echo "create table $table_name (account char (60) not null,subclassification char (35),hard_coded_account_key char (40)) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (account);" | sql.e '^' mysql
table_name=`get_table_name $application bank_upload`
echo "create table $table_name (bank_date date not null,bank_description char (140) not null,sequence_number integer,bank_amount double (10,2),bank_running_balance double (12,2),posted_yn char (1)) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (bank_date,bank_description);" | sql.e '^' mysql
table_name=`get_table_name $application day`
echo "create table $table_name (day char (9) not null) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (day);" | sql.e '^' mysql
table_name=`get_table_name $application depreciation`
echo "create table $table_name (full_name char (60) not null,street_address char (40) not null,depreciation_date date not null,purchase_date_time datetime,asset_name char (30),transaction_date_time datetime,serial_number char (10),units_produced integer,depreciation_amount double (10,2)) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (full_name,street_address,depreciation_date);" | sql.e '^' mysql
table_name=`get_table_name $application depreciation_method`
echo "create table $table_name (depreciation_method char (25) not null) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (depreciation_method);" | sql.e '^' mysql
table_name=`get_table_name $application element`
echo "create table $table_name (element char (20) not null,accumulate_debit_yn char (1)) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (element);" | sql.e '^' mysql
table_name=`get_table_name $application entity`
echo "create table $table_name (full_name char (60) not null,street_address char (40) not null,login_name char (50),city char (20),state_code char (2),zip_code char (10),phone_number char (15),cell_number char (15),email_address char (50)) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (full_name,street_address);" | sql.e '^' mysql
echo "create unique index ${table_name}_additional_unique on $table_name (login_name);" | sql.e '^' mysql
table_name=`get_table_name $application equity_account_balance`
echo "create unique index $table_name on $table_name (full_name,street_address,account_number,date_time);" | sql.e '^' mysql
table_name=`get_table_name $application financial_institution`
echo "create table $table_name (full_name char (60) not null,street_address char (40) not null) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (full_name,street_address);" | sql.e '^' mysql
table_name=`get_table_name $application fixed_asset`
echo "create table $table_name (asset_name char (30) not null,account char (60)) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (asset_name);" | sql.e '^' mysql
table_name=`get_table_name $application fixed_asset_purchase`
echo "create unique index $table_name on $table_name (full_name,street_address,purchase_date_time,asset_name,serial_number);" | sql.e '^' mysql
table_name=`get_table_name $application investment_account`
echo "create unique index $table_name on $table_name (full_name,street_address,account_number);" | sql.e '^' mysql
table_name=`get_table_name $application investment_classification`
echo "create table $table_name (classification char (15) not null) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (classification);" | sql.e '^' mysql
table_name=`get_table_name $application investment_operation`
echo "create table $table_name (investment_operation char (15) not null) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (investment_operation);" | sql.e '^' mysql
table_name=`get_table_name $application journal_ledger`
echo "create table $table_name (full_name char (60) not null,street_address char (40) not null,transaction_date_time datetime not null,account char (60) not null,transaction_count integer,previous_balance double (10,2),debit_amount double (10,2),credit_amount double (10,2),balance double (11,2)) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (full_name,street_address,transaction_date_time,account);" | sql.e '^' mysql
table_name=`get_table_name $application prior_fixed_asset`
echo "create unique index $table_name on $table_name (asset_name,serial_number);" | sql.e '^' mysql
table_name=`get_table_name $application prior_fixed_asset_depreciation`
echo "create table $table_name (full_name char (60) not null,street_address char (40) not null,asset_name char (30) not null,serial_number char (10) not null,depreciation_date date not null,depreciation_amount double (10,2),transaction_date_time datetime) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (full_name,street_address,asset_name,serial_number,depreciation_date);" | sql.e '^' mysql
table_name=`get_table_name $application purchase_order`
echo "create unique index $table_name on $table_name (full_name,street_address,purchase_date_time);" | sql.e '^' mysql
table_name=`get_table_name $application receipt_upload`
echo "create table $table_name (receipt_upload_filename char (80) not null,upload_date date,posted_yn char (1)) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (receipt_upload_filename);" | sql.e '^' mysql
table_name=`get_table_name $application reoccurring_transaction`
echo "create table $table_name (full_name char (60) not null,street_address char (40) not null,debit_account char (60),credit_account char (60),transaction_amount double (10,2)) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (full_name,street_address);" | sql.e '^' mysql
table_name=`get_table_name $application self`
echo "create unique index $table_name on $table_name (full_name,street_address);" | sql.e '^' mysql
table_name=`get_table_name $application service_purchase`
echo "create table $table_name (full_name char (60) not null,street_address char (40) not null,purchase_date_time datetime not null,account char (60) not null,service_description text,extension double (10,2)) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (full_name,street_address,purchase_date_time,account);" | sql.e '^' mysql
table_name=`get_table_name $application subclassification`
echo "create table $table_name (subclassification char (35) not null,element char (20),display_order integer) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (subclassification);" | sql.e '^' mysql
table_name=`get_table_name $application supply`
echo "create table $table_name (supply_name char (30) not null,account char (60)) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (supply_name);" | sql.e '^' mysql
table_name=`get_table_name $application supply_purchase`
echo "create table $table_name (full_name char (60) not null,street_address char (40) not null,purchase_date_time datetime not null,supply_name char (30) not null,quantity integer,unit_cost double (10,2),extension double (10,2)) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (full_name,street_address,purchase_date_time,supply_name);" | sql.e '^' mysql
table_name=`get_table_name $application tax_form`
echo "create table $table_name (tax_form char (20) not null) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (tax_form);" | sql.e '^' mysql
table_name=`get_table_name $application tax_form_line`
echo "create table $table_name (tax_form char (20) not null,tax_form_line char (5) not null,tax_form_description char (35),itemize_accounts_yn char (1)) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (tax_form,tax_form_line);" | sql.e '^' mysql
table_name=`get_table_name $application tax_form_line_account`
echo "create table $table_name (tax_form char (20) not null,tax_form_line char (5) not null,account char (60) not null) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (tax_form,tax_form_line,account);" | sql.e '^' mysql
table_name=`get_table_name $application transaction`
echo "create table $table_name (full_name char (60) not null,street_address char (40) not null,transaction_date_time datetime not null,memo char (60),transaction_amount double (10,2),check_number integer,lock_transaction_yn char (1)) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (full_name,street_address,transaction_date_time);" | sql.e '^' mysql
echo "create unique index ${table_name}_additional_unique on $table_name (transaction_date_time);" | sql.e '^' mysql
table_name=`get_table_name $application vendor`
echo "create table $table_name (full_name char (60) not null,street_address char (40) not null) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (full_name,street_address);" | sql.e '^' mysql
table_name=`get_table_name $application vendor_payment`
echo "create table $table_name (full_name char (60) not null,street_address char (40) not null,purchase_date_time datetime not null,payment_date_time datetime not null,payment_amount double (10,2),check_number integer,transaction_date_time datetime) engine MyISAM;" | sql.e '^' mysql
echo "create unique index $table_name on $table_name (full_name,street_address,purchase_date_time,payment_date_time);" | sql.e '^' mysql

(
cat << all_done2
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
insert into tax_form_line (	tax_form,
			tax_form_line,
			tax_form_description,
all_done2
) | sql.e 2>&1 | grep -vi duplicate


(
cat << all_done5
all_done5
) | sql.e 2>&1 | grep -vi duplicate


(
cat << all_done3
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process (process,
		command_line,
		notepad,
		html_help_file_anchor,
		process_set_display,
		process_group,
		preprompt_help_text,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
insert into process_parameter (process,
		folder,
		attribute,
		drop_down_prompt,
		prompt,
		display_order,
		drop_down_multi_select_yn,
		preprompt_yn,
		populate_drop_down_process,
all_done3
) | sql.e 2>&1 | grep -vi duplicate


(
cat << all_done4
insert into self (full_name,
		street_address,
all_done4
) | sql.e 2>&1 | grep -vi duplicate

exit 0
