:
# migrate_bonefish_mkdir_data.sh
# ------------------------------

cd /opt/physical

mkdir data

cd data
mkdir acoustic
mkdir acoustic/GARDENKEY
mkdir acoustic/GARDENKEY/GARDENKEY_20151216
mkdir acoustic/BK
mkdir acoustic/BK/BK_20160706
mkdir acoustic/Indices
mkdir acoustic/Indices/index_utility
mkdir acoustic/Indices/index_utility/output
mkdir acoustic/JB
mkdir acoustic/JB/JB_20171116
mkdir acoustic/JB/JB_20160907
mkdir acoustic/JB/JB_20170523
mkdir acoustic/JB/JB_20151205
mkdir acoustic/JB/JB_20151205/Data
mkdir acoustic/LB
mkdir acoustic/LB/LB_20140806
mkdir acoustic/LM
mkdir acoustic/LM/LM_20160706
mkdir acoustic/LM/LM_20160907
mkdir acoustic/LM/LM_20170410
mkdir acoustic/LM/LM_20170410/raven_detect_tables
mkdir acoustic/DK
mkdir acoustic/DK/DK_20170523
mkdir acoustic/DK/DK_20170410
mkdir acoustic/DK/DK_20151207
mkdir acoustic/DK/DK_20151207/Data
mkdir acoustic/DK/DK_20161122
mkdir acoustic/DK/DK_20161122/DuckKey_Nov2016_RZ
mkdir acoustic/DK/DK_20161122/DuckKey_Nov2016_station
mkdir acoustic/DK/DK_20140804
mkdir lrgs
mkdir barracuda_backup
mkdir dailyplots
mkdir dailyplots/issues20151112
mkdir dailyplots/util
mkdir NOAA
mkdir NOAA/moorings
mkdir NOAA/moorings/northwest_adcp_d
mkdir NOAA/moorings/northwest_adcp_d/adcp
mkdir NOAA/moorings/northwest_adcp_d/adcp/plots
mkdir NOAA/moorings/northwest_adcp_d/adcp/ascii
mkdir NOAA/moorings/northwest_adcp_d/ct
mkdir NOAA/moorings/midbay
mkdir NOAA/moorings/midbay/ctd
mkdir NOAA/moorings/midbay/adcp
mkdir NOAA/moorings/midbay/cm
mkdir NOAA/moorings/midbay/ct
mkdir NOAA/moorings/midbay/ct/plots
mkdir NOAA/moorings/midbay/ct/ascii
mkdir NOAA/moorings/northeast_adcp_c
mkdir NOAA/moorings/northeast_adcp_c/adcp
mkdir NOAA/moorings/northeast_adcp_c/adcp/plots
mkdir NOAA/moorings/northeast_adcp_c/adcp/ascii
mkdir NOAA/moorings/northeast_adcp_c/ct
mkdir NOAA/moorings/southwest_adcp_b
mkdir NOAA/moorings/southwest_adcp_b/ctd
mkdir NOAA/moorings/southwest_adcp_b/adcp
mkdir NOAA/moorings/southwest_adcp_b/adcp/plots
mkdir NOAA/moorings/southwest_adcp_b/adcp/ascii
mkdir NOAA/moorings/southwest_adcp_b/ct
mkdir NOAA/moorings/southwest_adcp_b/ct/plots
mkdir NOAA/moorings/southwest_adcp_b/ct/ascii
mkdir NOAA/moorings/southeast_adcp_a
mkdir NOAA/moorings/southeast_adcp_a/adcp
mkdir NOAA/moorings/southeast_adcp_a/adcp/plots
mkdir NOAA/moorings/southeast_adcp_a/adcp/ascii
mkdir NOAA/moorings/southeast_adcp_a/ct
mkdir NOAA/moorings/southeast_adcp_a/ct/plots
mkdir NOAA/moorings/southeast_adcp_a/ct/ascii
mkdir NOAA/moorings/looe_key
mkdir NOAA/moorings/looe_key/adcp
mkdir NOAA/moorings/looe_key/adcp/plots
mkdir NOAA/moorings/looe_key/adcp/ascii
mkdir NOAA/moorings/looe_key/ct
mkdir NOAA/moorings/ct
mkdir NOAA/moorings/shark_river_1
mkdir NOAA/moorings/shark_river_1/ct
mkdir NOAA/moorings/shark_river_1/ct/plots
mkdir NOAA/moorings/shark_river_1/ct/ascii
mkdir NOAA/moorings/shark_river_3
mkdir NOAA/moorings/shark_river_3/ct
mkdir NOAA/moorings/shark_river_3/ct/plots
mkdir NOAA/moorings/shark_river_3/ct/ascii
mkdir NOAA/moorings/moser_channel
mkdir NOAA/moorings/moser_channel/ct
mkdir NOAA/moorings/moser_channel/ct/plots
mkdir NOAA/moorings/moser_channel/ct/ascii
mkdir gulfcoast
mkdir sharkslough
mkdir road_interior
mkdir dfe
mkdir dfe/modelLand
mkdir dfe/modelLand/greatgrandfather
mkdir dfe/modelLand/son
mkdir dfe/modelLand/son/untar
mkdir dfe/modelLand/grandfather
mkdir dfe/modelLand/father
mkdir dfe/modelLand/greatgreatgrandfather
mkdir dfe/benchmark
mkdir dfe/repair_measurement_20140611
mkdir dfe/sparrow
mkdir dfe/sparrow/greatgrandfather
mkdir dfe/sparrow/son
mkdir dfe/sparrow/grandfather
mkdir dfe/sparrow/father
mkdir dfe/sparrow/greatgreatgrandfather
mkdir dfe/hold
mkdir dfe/backup_line
mkdir dfe/backup_line/greatgrandfather
mkdir dfe/backup_line/son
mkdir dfe/backup_line/grandfather
mkdir dfe/backup_line/father
mkdir dfe/backup_line/greatgreatgrandfather
mkdir dfe/backup_block
mkdir dfe/backup_block/greatgrandfather
mkdir dfe/backup_block/son
mkdir dfe/backup_block/grandfather
mkdir dfe/backup_block/father
mkdir dfe/backup_block/greatgreatgrandfather
mkdir dfe/utility
mkdir dfe/utility/backups
mkdir dfe/updates_changes
mkdir dfe/updates_changes/usgs_coastal
mkdir data_problems
mkdir data_problems/geo
mkdir data_problems/bad_times
mkdir data_problems/bad_times/porewater
mkdir USGS_WRD
mkdir USGS_WRD/Gulf
mkdir USGS_WRD/Gulf/VLFinalDat
mkdir USGS_WRD/Gulf/VLFinalDat/H20
mkdir USGS_WRD/Gulf/VLFinalDat/WQual
mkdir USGS_WRD/Gulf/VLFinalDat/CPhys
mkdir USGS_WRD/Gulf/EPFinalDat
mkdir USGS_WRD/Gulf/EPFinalDat/Metadata
mkdir USGS_WRD/Gulf/EPFinalDat/Data
mkdir USGS_WRD/Gulf/EPFinalDat/Publications
mkdir USGS_WRD/FlaBay
mkdir USGS_WRD/FlaBay/DataSeries105
mkdir validation
mkdir taylor_slough
mkdir taylor_slough/stageDischarge
mkdir waterquality
mkdir waterquality/backup
mkdir waterquality/backup/greatgrandfather
mkdir waterquality/backup/son
mkdir waterquality/backup/grandfather
mkdir waterquality/backup/father
mkdir waterquality/backup/greatgreatgrandfather
mkdir sal_syn
mkdir presidentsDayMassacre
mkdir fathom_sal
mkdir fathom_sal/nsmsens31
mkdir fathom_sal/nsm
mkdir fathom_sal/util
mkdir fathom_sal/alt7r
mkdir fathom_sal/archive
mkdir WatchList
mkdir taylorslough_south
mkdir DERM_data
mkdir DRTO
mkdir requests
mkdir requests/bryanmccloskey
mkdir requests/damon
mkdir requests/frezza_peter
mkdir requests/frezza_peter/20160819
mkdir requests/frezza_peter/20070504
mkdir requests/frezza_peter/20060815
mkdir requests/flbay
mkdir requests/flbay/originals
mkdir requests/bisc
mkdir requests/bisc/trash
mkdir requests/turcotteSal
mkdir requests/turcotteSal/sent
mkdir requests/matthew_petkewich
mkdir requests/matthew_petkewich/20160606
mkdir requests/matthew_petkewich/20170306
mkdir requests/mikeshe
mkdir requests/mikeshe/sent
mkdir requests/ReneRain
mkdir requests/ReneRain/to_rene
mkdir requests/kaylee_rice
mkdir requests/kaylee_rice/2013_Apr
mkdir requests/kaylee_rice/2007_Oct
mkdir requests/kaylee_rice/2012_Aug
mkdir requests/hydrology
mkdir requests/lapuma
mkdir requests/eden_2006
mkdir requests/mario_20120921
mkdir requests/mario_20120921/1981
mkdir requests/mario_20120921/1992_2012
mkdir requests/zhixiao_xie
mkdir requests/sobczak
mkdir requests/chris_catano
mkdir requests/engel
mkdir requests/sfwmd_hourly
mkdir requests/eagle
mkdir requests/rosenblat
mkdir requests/lauraPaulik
mkdir requests/chase_rakowski
mkdir requests/simeon
mkdir requests/simeon/sent
mkdir requests/jemeema
mkdir requests/daily_values
mkdir requests/daily_values/old
mkdir requests/SylviaLee
mkdir requests/flBam
mkdir requests/kelble
mkdir requests/stith
mkdir requests/stith/sent
mkdir requests/CarissaGervasi
mkdir requests/CarissaGervasi/20180208
mkdir requests/CarissaGervasi/20180208/csv_files_20180208
mkdir requests/CarissaGervasi/20180208/pipe_files_20180208
mkdir requests/CarissaGervasi/20180125
mkdir requests/CarissaGervasi/20180125/csv_files
mkdir requests/validation_level
mkdir requests/eden
mkdir requests/philip_matich
mkdir requests/robin
mkdir requests/robin/bennett2
mkdir requests/robin/bennett
mkdir requests/fws
mkdir requests/rena
mkdir requests/rena/sent
mkdir requests/kiren
mkdir requests/kirenbiscjobert2004-2007
mkdir requests/amy
mkdir requests/amy/20120122
mkdir requests/amy/20130116
mkdir requests/amy/20130116/amy
mkdir requests/amy/20130116/amy2
mkdir requests/audubon
mkdir requests/audubon/sent
mkdir requests/audubon/util
mkdir requests/skip
mkdir requests/WilliamBooth
mkdir requests/bisc_noval
mkdir requests/turcotte
mkdir requests/turcotte/sent
mkdir requests/turcotte/hold
mkdir requests/turcotte/pors
mkdir requests/brandon_gamble
mkdir requests/por
mkdir requests/rolando_santos_corujo
mkdir requests/graves
mkdir requests/kirenbisc
mkdir requests/fahmida
mkdir requests/fahmida/sent
mkdir requests/util
mkdir requests/util/backups
mkdir requests/data
mkdir requests/frank_marshall
mkdir requests/roy
mkdir requests/reneprice
mkdir requests/reneprice/today
mkdir requests/bisc_redo
mkdir requests/Deposition
mkdir requests/Deposition/NP205
mkdir requests/Deposition/SubPoPA
mkdir requests/Deposition/emails
mkdir requests/Deposition/memos
mkdir requests/kirenbiscjobert
mkdir requests/ikuko_fujisaki
mkdir requests/linden
mkdir requests/ad_hoc
mkdir requests/eric_carlson
mkdir requests/hunter_clasen
mkdir requests/troxler
mkdir requests/troxler/20110804
mkdir requests/kimHanes
mkdir requests/rene
mkdir requests/rene/sent
mkdir requests/rene/20130306
mkdir requests/rene/20130306/data
mkdir requests/mario_2011-02-17
mkdir requests/jenkins
mkdir requests/jenkins/sent
mkdir requests/sfwmm
mkdir requests/julie
mkdir requests/aviation_depth
mkdir requests/aviation_depth/backups
mkdir requests/kirenjobertsalinity2011
mkdir requests/lter
mkdir requests/lter/flow_done
mkdir requests/lter/done
mkdir requests/lter/powell
mkdir requests/lter/stage_done
mkdir requests/lter/stage_done/trash
mkdir requests/lter/gordons
mkdir requests/lter/correspondence
mkdir requests/sfwmd
mkdir requests/sfwmd/sent
mkdir requests/sfwmd/Everglades_National_Park_MMN_2003
mkdir requests/sfwmd_mmn
mkdir requests/vivek
mkdir requests/vivek/sent
mkdir requests/L30Seepage
mkdir requests/jason
mkdir requests/marc
mkdir requests/Zapata
mkdir requests/Zapata/sent
mkdir requests/joel
mkdir requests/joel/graceTest
mkdir requests/joel/sent
mkdir requests/joel/hold
mkdir requests/kev
mkdir requests/sashi
mkdir requests/hernandez
mkdir requests/rehage
mkdir requests/trail_discharge
mkdir usgs_brd
mkdir survey_field_sheets
mkdir taylorslough_north
mkdir Lorenz
mkdir metadata
mkdir eden
mkdir eden/Quarterly_Surface_Zipfiles
mkdir eden/output.tif
mkdir eden/Quarterly_Depth_Zipfiles
mkdir paleo_NSM_target
mkdir NOAH_IV
mkdir NOAH_IV/Archive
mkdir NOAH_IV/Archive/copy
mkdir OracleDump
mkdir OracleDump/scripts
mkdir CapeSable
mkdir mlr_sal
mkdir floridabay_west
mkdir ET
mkdir uvnet
mkdir uvnet/RV
mkdir uvnet/RV/1998
mkdir uvnet/RV/1999
mkdir uvnet/RV/2003
mkdir uvnet/RV/2001
mkdir uvnet/RV/2002
mkdir uvnet/RV/2000
mkdir uvnet/RV/1997
mkdir uvnet/RV/2004
mkdir uvnet/util
mkdir uvnet/SV
mkdir uvnet/SV/1998
mkdir uvnet/SV/1999
mkdir uvnet/SV/2003
mkdir uvnet/SV/2001
mkdir uvnet/SV/2002
mkdir uvnet/SV/2000
mkdir uvnet/SV/1997
mkdir uvnet/SV/2004
mkdir fl_bay
mkdir trail_flow
mkdir road_exterior
mkdir Topo
mkdir Topo/corpsTopoSouthofTrail
mkdir sfwmd_data
mkdir sfwmd_data/C111Load
mkdir sfwmd_data/C111Load/Data
mkdir sfwmd_data/C111Load/Data/Rec
mkdir sfwmd_data/C111Load/Data/20070928
mkdir sfwmd_data/C111Load/Data/20070928/Primary
mkdir sfwmd_data/C111Load/Data/Work
mkdir sfwmd_data/C111Load/Data/Work/X
mkdir sfwmd_data/C111Load/Data/Work/Z
mkdir sfwmd_data/C111Load/Data/Work/Y
mkdir sfwmd_data/C111Load/Data/20080416
mkdir sfwmd_data/C111Load/Data/20080416/Primary
mkdir sfwmd_data/C111Load/Data/20080416/Msg
mkdir usgs_load
mkdir usgs_load/data_man
mkdir usgs_load/data_man/unvalid_data
mkdir usgs_load/data_man/unvalid_data/records
mkdir usgs_load/2loadx
mkdir usgs_load/2loadx/loaded
mkdir usgs_load/2load07
mkdir usgs_load/2Reload
mkdir usgs_load/util
mkdir usgs_load/loaded
mkdir usgs_load/2update
mkdir usgs_load/2update/updated
mkdir usgs_load/2load
mkdir gitStuff
mkdir gitStuff/ENPMS
mkdir gitStuff/ENPMS/.git
mkdir gitStuff/ENPMS/.git/objects
mkdir gitStuff/ENPMS/.git/objects/db
mkdir gitStuff/ENPMS/.git/objects/dc
mkdir gitStuff/ENPMS/.git/objects/c8
mkdir gitStuff/ENPMS/.git/objects/d4
mkdir gitStuff/ENPMS/.git/objects/pack
mkdir gitStuff/ENPMS/.git/objects/d0
mkdir gitStuff/ENPMS/.git/objects/87
mkdir raw_data
mkdir raw_data/BISC
mkdir raw_data/wilma
mkdir raw_data/wilma/DOY_294
mkdir raw_data/hold
mkdir raw_data/append
mkdir raw_data/Folder Settings
mkdir raw_data/archive
mkdir raw_data/208w_temp_backup
mkdir raw_data/208w_temp_backup/208W
mkdir raw_data/208w_temp_backup/208W/Rawdata
mkdir raw_data/208w_temp_backup/208W/Daily_Rawdata
mkdir raw_data/208w_temp_backup/DATA_backup
mkdir raw_data/208w_temp_backup/DATA_backup/PC208W
mkdir raw_data/208w_temp_backup/DATA_backup/INIFILES
mkdir raw_data/208w_temp_backup/DATA_backup/SCRIPTS
mkdir raw_data/208w_temp_backup/DATA_backup/BIN
mkdir raw_data/208w_temp_backup/DATA_backup/BIN/INIFILES
mkdir raw_data/208w_temp_backup/DATA_backup/RAWDATA
mkdir raw_data/208w_temp_backup/DATA_backup/RAWDATA/RAWDATA_old
mkdir dbkey_analysis
mkdir dbkey_analysis/trash
mkdir taylor_slough_files
mkdir irma
mkdir mink
mkdir station_photos
mkdir floridabay_east
mkdir archive
mkdir archive/usbBackUP20151029
mkdir archive/CSable
mkdir archive/export_enpdata
mkdir archive/export_enpdata_done
mkdir station
mkdir kev
mkdir BBSM
mkdir BBSM/COCA_low
mkdir BBSM/COCA_high
mkdir BBSM/COCA_mid
mkdir BBSM/COCA_base
mkdir joe_bay_usgs
mkdir Tree_Island

exit 0
